sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: UeF0oy5oOUpUcUqTGJrOpGJdVHeyk19sKAVYEYfBXSwjqkYFyNqadhnS7mLt0wN8pFW/nu1rH+SUDkIb2YlFXtRySMZgAtwotCms5E0VCKLPosq79Xc5pu05JN9SvodzZSzZUh4GqoceD+whJoQuPamTcCh6zhfLAtKK6a1TjjqrGWVpFEKzzY/u88h1/z2oW0bA/SATrV0P2IRLjthapJ2Aa+fW0wfeWPnIsQfBJnatRbBesYgYeV34CAx6vKs43c1hJZBVn+UDKjH+bUIvOgQ2Jo/6rI4OzHOW+V4V2ZLPhsl3pXpFRA9NZzBVhiUBrcgYkWOrpGECRc9jnoCvhAVjQgspv7u4WUdRQ+PWzI21UVLUOWY6VqbBlhiRnRmhxgxw9MJ5wnyedZSIoKMZDIqE2fQRx4aqEfplqhsn/+Aw4ydY/k5ZWOVx31sJ9nRhiTjKN4yW+LFe9rYB9zndOMDTv7LBLyJvffaQu5tTtV3MpbH6Q21Zisb6FgJz685NO45SQdnhyvQ7h7RqaMkA8b1X82etbaGg3PIrpo6VZnWIVrkksnIOlgzzJ4q9btM9cLii9bWpESB5rpS/kRYdMDE4EmZM7plsFgkrl4sQzStvwAb0JeFsZTQz5ueKTBXeK75YXgI1hdcbCaOQdxM8hEu9nvhGoNAQ/4TGST+6aVY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Agnes-Grey_767
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy